### PR TITLE
New icon

### PR DESCRIPTION
**Pull request by kosijer**
Hopefully this version will work

image

Feel free to give me some suggestions

### CODE REVIEW

**Comment by bartzaalberg** [comment]
Looks cool! I wonder how it looks outlines to make it a bit more elementary themed. Could you try that out for me?

**Comment by bartzaalberg** [comment]
Also is this for the crown inside of the application? Or is this as desktop shortcut icon. Or maybe both which could be awesome too :) Because you only replaced the crown icon instead of the desktop shortcut icon.

**Comment by bartzaalberg** [comment]
example
I meant circles like these. This one is from the elementary spotify icon

**Comment by kosijer** [comment]
Thanks @bartzaalberg for the suggestion.
You meant something like this? 

image


I just replaced the one icon I found. Actually there were other icon folders inside `data/icons/` but I didn't know if I should replace them as they had different layout.

**Comment by bartzaalberg** [comment]
Yes nice!

**Comment by bartzaalberg** [comment]
But the icon you edited is actually an icon for inside of the app. Could you replace the icons in data/icons with this one and the one in data/ with only the same icon but without the shadow?

**Comment by bartzaalberg** [comment]
It took a bit long so i added i took the liberty of  adjusting it to your png myself. Thanks! i love it Red is also now the main colour of the application.

**Comment by kosijer** [comment]
Could you restore this PR?

**Comment by kosijer** [comment]
I created the new PR here https://github.com/bartzaalberg/lottery/pull/3

**Pull request closed without merging**
